Repository jflatdb/jflatdb, pull requests merged in 2025-10, with the labels that each got.

#9 Add Example Script for jflatdb
  data/users.json
  examples/basic_usage.py
  jflatdb/indexer.py
  logs/db.log
Labels: hacktoberfest-accepted, hacktoberfest-2025

#25 Issue #21 : Feature/query caching
  CACHING.md
  cache_demo.py
  jflatdb/__pycache__/__init__.cpython-313.pyc
  jflatdb/__pycache__/database.cpython-313.pyc
  jflatdb/__pycache__/indexer.cpython-313.pyc
  jflatdb/__pycache__/query_engine.cpython-313.pyc
  jflatdb/__pycache__/schema.cpython-313.pyc
  jflatdb/__pycache__/security.cpython-313.pyc
  jflatdb/__pycache__/storage.cpython-313.pyc
  jflatdb/database.py
  jflatdb/exceptions/__pycache__/errors.cpython-313.pyc
  jflatdb/query_cache.py
  jflatdb/utils/__pycache__/__init__.cpython-313.pyc
  jflatdb/utils/__pycache__/logger.cpython-313.pyc
  logs/db.log
  tests/test_query_cache.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest-2025

#34 Added DISTINCT Function to QueryEngine , So;lved #26
  docs/QUERY_ENGINE.md
  jflatdb/query_engine.py
  tests/test_distinct.py
Labels: enhancement, good first issue
